name: HeavenActivity
main: tk.tyzoid.plugins.HeavenActivity.HeavenActivity
version: 2.0.0a
author: Tyzoid
permissions:
    heavenactivity.*:
        description: Gives access to all heavenactivity commands
        children:
            heavenactivity.foo: true
            heavenactivity.bar: true
    heavenactivity.foo:
        description: Allows people to use /foo
        default: OP
    heavenactivity.bar
        description: Allows people to use /bar
        default: OP