name: HeavenActivity
main: tk.tyzoid.plugins.HeavenActivity.HeavenActivity
version: 2.0.1
author: Tyzoid
softdepend: [BOSEconomy, Essentials, iConomy, MultiCurrency]
permissions:
    activity.view.*:
        description: Allows to view all information
        children:
            activity.view.own: true
            activity.view.other: true
            activity.view.list: true
    activity.view.own:
        description: Allows to view own activity with /activity
        default: true
    activity.view.other:
        description: Allows to view activity of other players with /activity (name)
        default: true
    activity.view.list:
        description: Allows to view a list of players and their current activity with /activity list
        default: true
    activity.notify:
        description: Sends regular notifications about activity and income
        default: true
    activity.admin.*:
        description: Allows admin stuff
        default: op